In [1]:
import calendar
import pandas as pd

years = [2016]

#Data sets
dataPRR = [[4, 1, 7], [5, 1, 7], [7, 1, 5], [8, 1, 7], [9, 1, 11], [10, 1, 11], [11, 1, 8], [12, 1, 3], [13, 1, 3], [14, 1, 2], [15, 1, 3], [18, 1, 7], [19, 1, 4], [20, 1, 6], [22, 1, 2], [25, 1, 6], [26, 1, 5], [27, 1, 9], [28, 1, 9], [29, 1, 8], [1, 2, 5], [2, 2, 6], [3, 2, 7], [4, 2, 10], [5, 2, 7], [6, 2, 1], [8, 2, 8], [9, 2, 6], [10, 2, 7], [11, 2, 7], [12, 2, 7], [13, 2, 1], [15, 2, 8], [16, 2, 4], [17, 2, 6], [18, 2, 2], [19, 2, 2], [20, 2, 4], [21, 2, 5], [22, 2, 6], [23, 2, 4], [24, 2, 5], [25, 2, 4], [26, 2, 3], [29, 2, 5], [1, 3, 7], [2, 3, 7], [3, 3, 7], [4, 3, 7], [7, 3, 8], [8, 3, 5], [9, 3, 7], [10, 3, 6], [11, 3, 8], [12, 3, 12], [13, 3, 11], [14, 3, 8], [15, 3, 7], [16, 3, 8], [17, 3, 4], [18, 3, 6], [21, 3, 4], [22, 3, 6], [23, 3, 7], [28, 3, 1], [29, 3, 2], [31, 3, 1], [1, 4, 6], [2, 4, 12], [3, 4, 10], [11, 4, 8], [12, 4, 7], [13, 4, 6], [14, 4, 6], [15, 4, 9], [18, 4, 9], [19, 4, 9], [20, 4, 5], [22, 4, 5], [25, 4, 5], [26, 4, 6], [27, 4, 3], [28, 4, 2], [29, 4, 2], [3, 5, 9], [4, 5, 6], [5, 5, 7], [6, 5, 8], [9, 5, 8], [10, 5, 8], [11, 5, 4], [12, 5, 7], [13, 5, 2], [14, 5, 12], [15, 5, 11], [17, 5, 7], [18, 5, 2], [19, 5, 6], [20, 5, 2], [23, 5, 5], [24, 5, 5], [25, 5, 8], [26, 5, 8], [27, 5, 4], [30, 5, 5], [31, 5, 2], [1, 6, 8], [2, 6, 2], [3, 6, 7], [6, 6, 5], [7, 6, 8], [8, 6, 8], [9, 6, 8], [10, 6, 8], [11, 6, 7], [12, 6, 8], [13, 6, 5], [14, 6, 6], [15, 6, 2], [16, 6, 3], [17, 6, 7], [20, 6, 8], [21, 6, 6], [22, 6, 7], [23, 6, 3], [24, 6, 6], [27, 6, 3], [29, 6, 2], [30, 6, 2], [1, 7, 7], [18, 7, 8], [19, 7, 8], [20, 7, 8], [21, 7, 8], [22, 7, 7], [23, 7, 11], [24, 7, 11], [26, 7, 10], [27, 7, 6], [28, 7, 8], [29, 7, 10], [1, 8, 7], [2, 8, 8], [3, 8, 9], [4, 8, 7], [5, 8, 7], [8, 8, 10], [9, 8, 7], [10, 8, 7], [11, 8, 6], [12, 8, 5], [13, 8, 11], [14, 8, 11], [16, 8, 9], [17, 8, 3], [18, 8, 7], [19, 8, 7], [22, 8, 6], [23, 8, 3], [24, 8, 4], [25, 8, 6], [26, 8, 5], [29, 8, 3], [30, 8, 1], [31, 8, 3], [1, 9, 7], [2, 9, 7], [3, 9, 10], [4, 9, 7], [5, 9, 9], [6, 9, 5], [7, 9, 4], [8, 9, 3], [9, 9, 3], [12, 9, 6], [13, 9, 4], [14, 9, 8], [15, 9, 6], [16, 9, 5], [19, 9, 7], [20, 9, 2], [21, 9, 6], [22, 9, 5], [23, 9, 5], [26, 9, 4], [27, 9, 6], [28, 9, 4], [29, 9, 2], [30, 9, 4], [1, 10, 12], [2, 10, 11], [3, 10, 6], [4, 10, 7], [5, 10, 4], [6, 10, 8], [7, 10, 7], [10, 10, 9], [11, 10, 7], [13, 10, 5], [14, 10, 2], [17, 10, 8], [18, 10, 5], [19, 10, 3], [20, 10, 7], [21, 10, 7], [14, 11, 1]]
dataCOR = [[7, 1, 1, 2], [13, 1, 2, 1], [14, 1, 4, 3], [15, 1, 3, 1], [18, 1, 2, 1], [20, 1, 1, 0], [25, 1, 1, 0], [26, 1, 1, 0], [27, 1, 1, 0], [29, 1, 1, 0], [1, 2, 5, 2], [2, 2, 1, 1], [5, 2, 1, 0], [9, 2, 1, 1], [11, 2, 1, 0], [12, 2, 1, 0], [15, 2, 2, 1], [16, 2, 3, 1], [18, 2, 4, 5], [19, 2, 3, 3], [20, 2, 1, 3], [21, 2, 3, 4], [22, 2, 3, 2], [23, 2, 4, 2], [24, 2, 1, 0], [25, 2, 1, 0], [26, 2, 1, 0], [29, 2, 2, 1], [3, 3, 1, 0], [8, 3, 2, 0], [10, 3, 1, 0], [14, 3, 1, 0], [15, 3, 1, 1], [17, 3, 2, 1], [18, 3, 1, 0], [21, 3, 2, 3], [22, 3, 3, 1], [23, 3, 1, 0], [30, 3, 2, 1], [31, 3, 3, 2], [1, 4, 1, 2], [3, 4, 2, 1], [14, 4, 4, 1], [19, 4, 1, 0], [20, 4, 2, 1], [22, 4, 1, 0], [25, 4, 2, 1], [26, 4, 2, 1], [27, 4, 2, 1], [28, 4, 4, 3], [4, 5, 1, 2], [5, 5, 1, 1], [11, 5, 1, 0], [12, 5, 2, 0], [23, 5, 1, 1], [25, 5, 1, 0], [27, 5, 1, 1], [31, 5, 2, 2], [3, 6, 1, 2], [6, 6, 1, 1], [11, 6, 1, 1], [12, 6, 1, 1], [13, 6, 3, 2], [14, 6, 1, 0], [24, 6, 1, 1], [27, 6, 1, 0], [28, 6, 2, 3], [30, 6, 1, 0], [22, 7, 1, 0], [29, 7, 2, 1], [1, 8, 2, 1], [2, 8, 1, 0], [3, 8, 1, 0], [4, 8, 4, 2], [5, 8, 1, 0], [12, 8, 1, 3], [14, 8, 1, 0], [17, 8, 1, 0], [18, 8, 3, 1], [23, 8, 2, 1], [24, 8, 3, 1], [25, 8, 2, 0], [26, 8, 1, 0], [29, 8, 2, 1], [30, 8, 5, 5], [31, 8, 3, 2], [3, 9, 1, 0], [4, 9, 1, 1], [6, 9, 3, 3], [7, 9, 2, 1], [8, 9, 3, 2], [15, 9, 2, 1], [16, 9, 1, 0], [19, 9, 2, 1], [20, 9, 7, 5], [21, 9, 1, 0], [26, 9, 1, 1], [27, 9, 1, 0], [29, 9, 4, 2], [30, 9, 2, 2], [3, 10, 2, 1], [5, 10, 2, 1], [11, 10, 2, 1], [13, 10, 1, 0], [14, 10, 2, 2], [18, 10, 4, 2], [19, 10, 5, 4], [24, 10, 2, 7], [26, 10, 3, 2]]

datasets = [dataPRR, dataCOR]
codification = ['PRR', 'COR']
partial_results = []
total_result = []


#Functions
def str_month(value, month):
    return str(value) + "/" + str(month)

def replace_empty_days(list_2d, symbol):
    for single_row in list_2d:
        for i, item in enumerate(single_row):
            if item.find('/') != -1:
                single_row[i] = symbol
    return list_2d

def find_replace(dataSR, data_calendar):
    for row in dataSR:
        for single_row in data_calendar:
            for i, item in enumerate(single_row):
                    if item == str(int(row[0])) + "/" + str(int(row[1])):
                        single_row[i] = str(row[2])
    return data_calendar

def calendar(year):
    import calendar
    monday, tuesday, wednesday, thursday, friday, saturday, sunday = ['L'],['M'],['X'],['J'],['V'],['S'],['D']
    weekday_rows_lists = [monday, tuesday, wednesday, thursday, friday, saturday, sunday]
    all_rows = []
    first_row = ['d\M']
    for month in range(1, 13):
        month_matrix = map(list, zip(*calendar.monthcalendar(year, month)))
        first_row += [str(calendar.month_name[month][:3])]
        first_row += [str('')] * (len(month_matrix[0]) -1)        
        for index, weekday_row in enumerate(month_matrix):
            weekday_rows_lists[index] += [str_month(x, month) for x in ','.join(map(str, month_matrix[index])).split(',')]
    all_rows.append(first_row)

    for element in weekday_rows_lists:
        all_rows.append(element)
    return all_rows

In [2]:
total_result = []
for year in years:
    for index, dataset in enumerate(datasets):
        calendar_tg = calendar(year)
        #Find and replace
        calendar_tg = find_replace(datasets[index], calendar_tg)
        #Replace empty days
        calendar_tg = replace_empty_days(calendar_tg, '')
        #Adding codification row
        code_row = [codification[index]] + [''] * (len(calendar_tg[0])-1)
        calendar_tg.insert(0, code_row)
        total_result += calendar_tg
        partial_results.append(calendar_tg)

In [6]:
df = pd.DataFrame.from_records(total_result)
df

     0    1   2  3  4  5    6  7  8  9  ...   53 54 55 56 57   58 59 60 61 62
0   PRR                                 ...
1   d\M  Jan               Feb          ...  Nov              Dec
2     L        7  8  7  6    5  8  8  6 ...          1
3     M        7  3  4  5    6  6  4  4 ...
4     X           3  6  9    7  7  6  5 ...
5     J        5  2     9   10  7  2  4 ...
6     V        7  3  2  8    7  7  2  3 ...
7     S       11             1  1  4    ...
8     D       11                   5    ...
9   COR                                 ...
10  d\M  Jan               Feb          ...  Nov              Dec
11    L              2  1    5     2  3 ...
12    M                 1    1  1  3  4 ...
13    X           2  1  1             1 ...
14    J        1  4             1  4  1 ...
15    V           3     1    1  1  3  1 ...
16    S                            1    ...
17    D                            3    ...

[18 rows x 63 columns]

In [7]:
df = pd.DataFrame.from_records(partial_results[0])
df

    0    1   2  3  4  5    6  7  8  9  ...   53 54 55 56 57   58 59 60 61 62
0  PRR                                 ...
1  d\M  Jan               Feb          ...  Nov              Dec
2    L        7  8  7  6    5  8  8  6 ...          1
3    M        7  3  4  5    6  6  4  4 ...
4    X           3  6  9    7  7  6  5 ...
5    J        5  2     9   10  7  2  4 ...
6    V        7  3  2  8    7  7  2  3 ...
7    S       11             1  1  4    ...
8    D       11                   5    ...

[9 rows x 63 columns]

In [8]:
df = pd.DataFrame.from_records(partial_results[1])
df

    0    1  2  3  4  5    6  7  8  9  ...   53 54 55 56 57   58 59 60 61 62
0  COR                                ...
1  d\M  Jan              Feb          ...  Nov              Dec
2    L             2  1    5     2  3 ...
3    M                1    1  1  3  4 ...
4    X          2  1  1             1 ...
5    J       1  4             1  4  1 ...
6    V          3     1    1  1  3  1 ...
7    S                           1    ...
8    D                           3    ...

[9 rows x 63 columns]